version: '3.8'

services:
  clap2diffusion:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: clap2diffusion:latest
    container_name: clap2diffusion
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128
    volumes:
      - ../:/workspace
      - ../data:/workspace/data
      - ../checkpoints:/workspace/checkpoints
      - ../outputs:/workspace/outputs
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "7860:7860"  # Gradio port
      - "8888:8888"  # Jupyter port (optional)
      - "6006:6006"  # Tensorboard port (optional)
    shm_size: '16gb'
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]